{{- if and (eq .Values.storage.backend "local") .Values.storage.persistence.enabled (not .Values.storage.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "eatpaper-api.fullname" . }}-receipts
  labels:
    {{- include "eatpaper-api.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.persistence.accessModes | nindent 4 }}
  {{- if .Values.storage.persistence.storageClass }}
  storageClassName: {{ .Values.storage.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
{{- end }}
